# Import essential libraries

In [1]:
# import libraries
import pandas as pd # for data manupulation or analysis
import numpy as np # for numeric calculation

# Data Load

In [2]:
df=pd.read_csv("/Users/upend/Downloads/assessment/data.csv",header=None,names=['TA','Course_Instructor','Course','Semester','Class_size','Class_Attribute'])

In [3]:
df.head(10)

TA  Course_Instructor  Course  Semester  Class_size  Class_Attribute
0   1                 23       3         1          19                3
1   2                 15       3         1          17                3
2   1                 23       3         2          49                3
3   1                  5       2         2          33                3
4   2                  7      11         2          55                3
5   2                 23       3         1          20                3
6   2                  9       5         2          19                3
7   2                 10       3         2          27                3
8   1                 22       3         1          58                3
9   2                 15       3         1          20                3

In [4]:
df.shape

(151, 6)

In [5]:
df.isnull().sum()

TA                   0
Course_Instructor    0
Course               0
Semester             0
Class_size           0
Class_Attribute      0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TA                 151 non-null    int64
 1   Course_Instructor  151 non-null    int64
 2   Course             151 non-null    int64
 3   Semester           151 non-null    int64
 4   Class_size         151 non-null    int64
 5   Class_Attribute    151 non-null    int64
dtypes: int64(6)
memory usage: 7.2 KB


In [7]:
df['Course_Instructor'].unique()

array([23, 15,  5,  7,  9, 10, 22, 13, 18,  6, 25,  2,  1,  8, 14, 21, 11,
       16,  4, 17, 20, 12, 24,  3, 19], dtype=int64)

In [8]:
df['Course'].unique()

array([ 3,  2, 11,  5, 22,  1, 21, 17, 25,  7,  9, 15, 13,  8, 16, 19, 14,
        6, 12, 18, 23, 26, 24, 20,  4, 10], dtype=int64)

# Split Dataset in train and test

In [9]:
X = df.drop("Class_Attribute", axis = 1)
y = df["Class_Attribute"]
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (151, 5)
Shape of y =  (151,)


In [10]:
from sklearn import preprocessing
normalized_X = preprocessing.normalize(X)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state= 8)
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (120, 5)
Shape of y_train =  (120,)
Shape of X_test =  (31, 5)
Shape of y_test =  (31,)


# Feature Scaling

# Machine Learning Model Training

In [13]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Linear Regression

In [14]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(random_state = 0)
lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)

accuracy_score(y_test, y_pred_lr)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.4838709677419355


# Support Vector Machine

In [15]:
# Support vector classifier
from sklearn.svm import SVC
svc_classifier = SVC()
svc_classifier.fit(X_train, y_train)
y_pred_scv = svc_classifier.predict(X_test)
accuracy_score(y_test, y_pred_scv)

0.3870967741935484

# K – Nearest Neighbor Classifier

In [16]:
# K – Nearest Neighbor Classifier
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_classifier.fit(X_train, y_train)
y_pred_knn = knn_classifier.predict(X_test)
accuracy_score(y_test, y_pred_knn)

0.41935483870967744

# Naive Bayes Classifier

In [17]:
# Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred_nb = nb_classifier.predict(X_test)
accuracy_score(y_test, y_pred_nb)

0.6451612903225806

# Decision Tree Classifier

In [18]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(criterion= 'entropy', random_state=3)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

accuracy_score(y_test, y_pred_dt)

0.7096774193548387

# Random Forest Classifier

In [19]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 51)
rf_classifier.fit(X_train, y_train)
y_pred_rf = rf_classifier.predict(X_test)
accuracy_score(y_test, y_pred_rf)

0.6774193548387096

# AdaBoost Classifier

In [20]:
# Adaboost Classifier
from sklearn.ensemble import AdaBoostClassifier
adb_classifier = AdaBoostClassifier(DecisionTreeClassifier(criterion = 'entropy', random_state = 200),
                                    n_estimators=2000,
                                    learning_rate=0.1,
                                    algorithm='SAMME.R',
                                    random_state=1,)
adb_classifier.fit(X_train, y_train)
y_pred_adb = adb_classifier.predict(X_test)
accuracy_score(y_test, y_pred_adb)

0.7741935483870968

In [21]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           1       0.69      0.85      0.76        13
           2       0.75      0.33      0.46         9
           3       0.73      0.89      0.80         9

    accuracy                           0.71        31
   macro avg       0.72      0.69      0.67        31
weighted avg       0.72      0.71      0.68        31



In [22]:
# Cross validation
from sklearn.model_selection import cross_val_score
cross_validation = cross_val_score(estimator = dt_model, X = X_train,y = y_train, cv = 10)
print("Cross validation accuracy of Decision Tree model = ", cross_validation)
print("\nCross validation mean accuracy of Decision Tree model = ", cross_validation.mean())

Cross validation accuracy of Decision Tree model =  [0.66666667 0.5        0.5        0.66666667 0.58333333 0.58333333
 0.58333333 0.41666667 0.58333333 0.25      ]

Cross validation mean accuracy of Decision Tree model =  0.5333333333333333


In [23]:
## Pickle
import pickle

# save model
pickle.dump(dt_model, open('Teaching_Assistant_ML_model.pickle', 'wb'))

# load model
ml_model_pl = pickle.load(open('Teaching_Assistant_ML_model.pickle', 'rb'))

# predict the output
y_pred_pl = ml_model_pl.predict(X_test)

# confusion matrix
cm_pl = confusion_matrix(y_test, y_pred_pl)
print('Confussion matrix = \n', cm_pl)

# show the accuracy
print("Accuracy of model = ",accuracy_score(y_test, y_pred_pl))

Confussion matrix = 
 [[11  1  1]
 [ 4  3  2]
 [ 1  0  8]]
Accuracy of model =  0.7096774193548387
